FROM golang:1.23-alpine 

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN mkdir -p /app/uploads/profiles /app/uploads/scanned

RUN go build -o main .

RUN adduser -D -g '' appuser && \
    chown -R appuser:appuser /app

USER appuser

EXPOSE 8080

CMD ["./main"]